version: "3.8"
services:

  dashboard-db:
    image: turtleshelldevelopment:database
    ports:
      - "3306:3306"
    volumes:
      - dashboard_db:/var/lib/mysql
    networks:
      - backend-dashboard
    environment:
      - MYSQL_ROOT_PASSWORD=SuperSecurePassword
  dashboard-nginx:
    image: turtleshelldevelopment:nginx
    ports:
      - "8090:80"
    networks:
      - backend-dashboard
      - frontend-dashboard
    volumes:
      - ./frontend/root:/frontend
  dashboard-backend:
    image: turtleshelldevelopment:backend
    ports:
      - "8091:8091"
    networks:
      - backend-dashboard

volumes:
  dashboard_db:

networks:
  backend-dashboard: {}
  frontend-dashboard: {}